version: "3.9"

services:
  db:
    image: postgres:14
    container_name: tm_postgres
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    expose:
      - ${PHX_PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${PHX_HOST}
    depends_on:
      - db

  webserver:
    build: ./webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
      - ./frontend/webserver/www:/var/www/certbot/:ro
      - ./frontend/webserver/conf/:/etc/nginx/ssl/:ro
    environment:
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - api

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./frontend/webserver/www/:/var/www/certbot/:rw
      - ./frontend/webserver/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  nginx_logs:
